spring.main.web-application-type=none
spring.main.banner-mode=off
logging.console.enabled=false

spring.ai.mcp.server.name=swmcp
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.stdio=true
spring.ai.mcp.server.type=SYNC

swapi.base-url=${SWAPI_BASE_URL:https://swapi.info}
