server.port=${PORT:8080}

spring.ai.mcp.server.name=swmcp
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp

swapi.base-url=${SWAPI_BASE_URL:https://swapi.info}
